bin/build

This is in order to continuously deploy stage from master, which we may want to reverse at some point if we set up a dev environment.

Create the version.json artifact unconditionally

---

missioncontrol/api/presto.py
missioncontrol/api/urls.py
missioncontrol/api/views.py

Uber-inflexible, but hopefully enough to get the UI running after some
more cleanup
Example that works with the sample data (at least as of this writing, the
interval will go out of date eventually): http://localhost:8000/api/windowed_aggregates/?measures=main_crashes&os_names=Windows_NT&channels=Other&interval=80000000

Strawman prototype of getting windowed aggregates via a raw sql statement

---

.dockerignore
Dockerfile

This makes installing version.json work again while still speeding things
up for the local dev case.

Copy everything in missioncontrol/ into docker container but use dockerignore

---

Makefile

The environment variable wasn't being passed to docker correctly,
so we were always defaulting to the current dev instance for the
API server

Fix building ui for docker

---

.env-dist
bin/test
docker-compose.yml

This allows us to modify variables for our development instance
(e.g. to use production presto)

Switch to using a .env file for setting environment variables

---

missioncontrol/etl/versions.py
missioncontrol/settings.py

We want it to be fairly low, as we want to display changes quickly.

Explicitly configure/set cache timeout of accessing the version endpoint

---

tox.ini

This is just to avoid reinstalling the python requirements in a new virtualenv on every test run.

Use system packages when running tox tests

---

frontend/ui/detailview.jsx

This saves us having to calculate it twice: once for the measure list, once
for khours. Since this operation is kind of slow (especially for longer time
ranges) we really only want to do it once.

Store seriesList as state in detail view

---

docker-compose.yml

This should save a small amount of bandwidth and setup for development
and ci cases. Partially fixes #128.

Use alpine variants of postgres and redis images for development

---

missioncontrol/etl/measure.py

It looks like athena isn't happy about the table being passed in as a quoted
parameter -- probably similar to the column we were already pre-formatting.
Let's try the same strategy as for that and see if it helps.

Fix querying configured table

---

frontend/schema.js
frontend/ui/detailview.jsx
package.json
yarn.lock

By default showing the 99th percentile of results (i.e. excluding the top
1%). Other options are 50, 75, 95, 100.

Add a percentile filter to detail view

---

frontend/ui/measuregraph.jsx

Small titles for series (i.e. version numbers) need less space than
buildids, may as well recover some extra space for that case.

Dynamically adjust amount of padding on graph to fit size of legend

---

frontend/ui/detailgraph.jsx
frontend/ui/detailview.jsx
frontend/ui/measuredetailgraph.jsx

We were previously updating the measure/time graphs in the detail view
every time any aspect of the global state changed, even when such a
state did not effect the graphs at all (e.g. the user was just changing
the time picker). This operation could be extremely slow when we're
visualizing a large amount of data. Use react's shouldComponentUpdate
functionality to avoid unnecessary updates.

Don't update graphs unnecessarily in detail view

---

frontend/ui/subview.jsx
missioncontrol/etl/measuresummary.py
missioncontrol/settings.py
tests/test_api.py
tests/test_etl_measure.py

Instead of giving a median of the previous version's counts at the present
time (which is quite biased), calculate the previous version's counts at the
same time as the present one. This helps account for skew as people first
start to update to a previous version.
Also add standard deviation to the API endpoint (not using it yet, will soon)

Make measure summary more meaningful

---

missioncontrol/settings.py

This prevents a cascade of scheduled tasks from clogging up the queue if
we're unable to run all the tasks that they themselves schedule every
5 minutes.

Expire beat tasks after a 5 minute delay

---

docs/API.md
missioncontrol/api/views.py
tests/test_api.py

This feature is not yet exposed in the UI, but useful for some data analysis
I want to do on the side.

Allow fetching just the measure data for specific versions

---

docs/API.md
frontend/ui/detailview.jsx
missioncontrol/api/views.py
tests/test_api.py

The first 24 hours of a release are extremely noisy, it's generally
best to ignore it when comparing releases after a sufficient amount
of time has passed.

Allow skipping the first 24 hours in relative release view

---

frontend/actions.js

We can at least show a "no data" screen instead of perpetually loading.
Even better would probably be to generally handle errors and show a
detailed error message, but that can come later.

Handle measure 404 in UI

---

missioncontrol/base/fixtures/base_metadata.yaml
missioncontrol/etl/measure.py

* Reduce "update interval" for release/esr to 6 weeks
* Only fetch data within the window of the update interval (instead of
everything)

Reduce maximum amount of data fetched

---

missioncontrol/etl/experiment.py
missioncontrol/etl/measure.py

* Skip negative measure counts -- in theory they should be rejected at the
ping validation level but this is not yet the case
(https://bugzilla.mozilla.org/show_bug.cgi?id=1447038)
* Allow zero-based measure counts (these can be useful for knowing that
we're counting stuff even if there are no errors to report)

Adjust how we handle negative and zero measure counts

---

missioncontrol/base/fixtures/base_metadata.yaml
missioncontrol/base/models.py
missioncontrol/etl/measure.py
missioncontrol/settings.py

On some channels, we needed to reduce it (i.e. linux or mac nightly or beta)
on others we want to increase it (linux release) to reduce the long tail of
random submitters we have to take into account.

Make minimum client count threshold used for presto configurable per-channel

---

frontend/ui/subview.jsx
missioncontrol/etl/measuresummary.py
tests/test_api.py
tests/test_etl_measure.py
tests/test_measuresummary.py

Sometimes it is useful to see the raw counts of various errors (esp. crashes)
for comparison with other tools or just generally.

Allow toggling between counts and rates on summary page

---

frontend/ui/measuredetailgraph.jsx

Only showing those below the percentile threshold could cause errors
if there are a low number of non-zero datapoints.

Show values that are *at* the percentile in detail view

---

missioncontrol/etl/measure.py
missioncontrol/etl/measuresummary.py
missioncontrol/etl/versions.py
tests/test_measuresummary.py

Version strings like 55.0b10 will come before 55.0b9 lexographically,
we need to modify our sql and presto queries accordingly.

Handle large beta numbers when querying / displaying data

---

missioncontrol/api/views.py

We can look at just the last 24 hours of results for getting the latest
buildid, instead of looking back through all time.

Speed up relative release api endpoint (fixes #258)

---

frontend/ui/subview.jsx

This is what we actually want, given that we are sorting a list that
normally includes a summary of each release number ('60') and *one*
specific beta/alpha/point release which is the latest ('59.0.3')

Use a variant of alphanumeric version sorting in release summary view

---

frontend/ui/subview.jsx
missioncontrol/api/views.py
tests/test_api.py

* Calculate it server side
* Use the highest number we have (since some measures might be out of date
if we haven't done a backfill for them)

Better calculation/rendering of latest version field duration

---

frontend/ui/detailgraph.jsx
yarn.lock

This involves upgrading (react) metrics-graphics and using the new(ish) rollover
time format parameter.

Rollovers in detail graphs now always show precise date/hour/minute

---

missioncontrol/etl/management/commands/load_measure_data.py
missioncontrol/etl/measure.py
missioncontrol/etl/measuresummary.py
missioncontrol/etl/tasks.py
missioncontrol/settings.py
tests/test_etl_measure.py

This is actually only a little more data per-query than getting the data
one-measure-at-a-time and allows us to hugely reduce both the number of
athena queries we make and the amount of time we spend making them.

Load all measures per platform/channel simultaneously (fixes #115)

---

frontend/ui/detailview.jsx

Filter based on an aggregate being less than or equal to the percentile,
rather than just less than. This avoids filtering out the entire dataset
if we just have zeros, which happens sometimes.

Fix filtering based on percentiles

---

frontend/ui/mainview.jsx
frontend/ui/platformcard.jsx

We are incorrectly calculating it based on a point release because of some
incorrectly refactored code.

Fix summary rate display in platform card

---

missioncontrol/etl/management/commands/load_measure_data.py

Allow loading/backfilling data for multiple channels/platforms/applications
at the same time from load_measure_data management command.

Streamline manual backfilling of data

---

frontend/schema.js
frontend/ui/detailview.jsx

Fixes #320.
Added MAX_VISIBLE_SERIES constant in `schema.js` and set it to 5.
Here is a screenshot which shows plots for 5 versions. 
Please let me know if this works. Also, should we add a button to set the MAX_VISIBLE_SERIES?
@wlach

Adds MAX_VISIBLE_SERIES const for showing detailed view

---

missioncontrol/etl/measure.py

Seems less necessary now that we are comparing all builds against
a whitelist of valid ones via buildhub. Hopefully this will help
get a small amount of extra nightly data on Linux and Mac.

Experiment with doing away with the minimum client count

---

missioncontrol/etl/measure.py
tests/test_etl_measure.py

We were throwing a list index error before in the measure etl code, which was
less than clear.

Throw a clearer exception in cases where we aren't getting builds from buildhub

---

frontend/test/components/__snapshots__/measuretable.spec.jsx.snap
frontend/test/components/measuretable.spec.jsx

Fixes #338. 
`lastUpdated` has been updated by a static function `Date.now = jest.fn(() => 1482363367071);`.
@wlach please review.

Fixes date issue in snapshot test

---

frontend/test/components/subview.spec.jsx
frontend/ui/subview.jsx
package.json
yarn.lock

Added patch for #335. 
I have added test for the same but the generated snapshot doesn't contain measureTable component. I've used mount instead of shallow rendering.
@wlach could you please help me with this?

Fix: Don't display measureTable when measures is empty

---

missioncontrol/etl/measuresummary.py
tests/test_measuresummary.py

The 99th percentile omits too many valid results on platform/channel/measure
combinations where there are very few events (e.g. Mac Nightly content
crashes). See https://bugzilla.mozilla.org/show_bug.cgi?id=1525359

Use the 99.9th percentile of results in rate calculations

---

missioncontrol/etl/builds.py
missioncontrol/etl/measure.py

This is expected in more recent versions of django, see: https://docs.djangoproject.com/en/1.8/topics/db/transactions/#controlling-transactions-explicitly

Wrap create operations that may fail in transaction.atomic

---

missioncontrol/settings.py

This should make sure slow etl operations complete.

Triple soft timeout limit for running celery tasks

---

missioncontrol/api/views.py

Platform order in postgres was changed because of the `UPDATE`s required.  This makes the order deterministic

Sort platforms by id

---

Dockerfile
docker-compose-ci.yml
missioncontrol/etl/measure.py

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1751861
With FF version 100 being released the SQL query is filtering out data incorrectly. The SQL query is filtering for example on `display_version > '97' AND display_version < '100'`. However the `'97'` string is actually "larger" than `'100'`. This explains the missing data and why values were lower for a while starting around March.
cc @whd

[Bug 1751861] Fix display_version comparison to account for 100+ versions
