LICENSE.txt
=> Add MPL2 LICENSE

missioncontrol/wsgi.py
Whoops, now that docker-compose is working again this circle build should succeed.
=> Add missing import

.neutrinorc.js, Makefile, frontend/schema.js, package.json, yarn.lock
This will let us test in a variety of environments (against a local vagrant
environment, against the dev server, against the production server...)
=> Make `SERVICE_DOMAIN` (the base url for the missioncontrol api server) variable

frontend/actions.js, frontend/reducers.js, frontend/schema.js, frontend/ui/dashboard.jsx, frontend/ui/detailview.jsx, frontend/ui/mainview.jsx, frontend/ui/subview.jsx, missioncontrol/api/views.py
Not the best code in the world, but it gets us into a working state
=> Just get the frontend working

.pyup.yml
Copied per g-k from https://github.com/mozilla-services/shavar/blob/master/.pyup.yml.
=> Configure pyup to only apply security updates

frontend/global.css, frontend/ui/dashboard.jsx, frontend/ui/detailview.jsx, frontend/ui/measuregraph.jsx, frontend/ui/subview.jsx, frontend/ui/subviewnav.jsx, package.json, yarn.lock
Vastly expand the space devoted to graphs, especially on larger screens.
Also make header permanently visible, and scroll graph/data area if needed.
=> Improve layout

frontend/ui/detailview.jsx
This fixes much of the lag we're seeing when changing filtering options
=> Stop unnecessarily updating react components in detail view

frontend/global.css, frontend/ui/dashboard.jsx
Make the scope of this project a little more clear to peoples.
=> Add "realtime telemetry" text to brand

Dockerfile
=> Some dockerfile improvements

frontend/ui/detailview.jsx
=> Show users timezone name below graphs in detailview

frontend/ui/subview.jsx
=> Display last updated time as relative

Dockerfile
See:
* https://github.com/mozilla/telemetry-analysis-service/commit/87fe752783dd487ab098c4ae312e209f1336fbfa#diff-3254677a7917c6c01f55212f86c57fbf
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866729
=> Work around an issue with postgresql installation in our docker image

frontend/global.css, frontend/ui/detailview.jsx
* Some formatting improvements
* Clicking on a buildid pop up the custom date range selector with a
corresponding interval
=> Improve buildid functionality in legend

missioncontrol/etl/measure.py, missioncontrol/settings.py, tests/test_etl_measure.py
These seem to be exclusively weird one off builds that weren't actually
released (or obscure custom builds, in the case of Linux).
=> Ignore aggregates with less than 100 clients in them

frontend/schema.js, frontend/ui/detailview.jsx, package.json, yarn.lock
WIP since I'm waiting on the mapping of measurements to process types in crashstats.
Otherwise, this now has the changes discussed in the issue.
=> Issue #162 - Crashstats url

frontend/ui/detailview.jsx
=> Make ordering of series in graph consistent

frontend/ui/dateselectormodal.jsx, frontend/ui/detailview.jsx
Even if we're only using it in one place (for now), the detail view is
getting rather unmanageably large.
=> Refactor date selector into its own component

frontend/ui/detailview.jsx
* Use has instead of get where possible
* Simplify getting boolean state of 'relative'
=> Cleanup some usage of urlParams

missioncontrol/api/views.py, missioncontrol/etl/experiment.py, missioncontrol/etl/management/commands/update_experiment_list.py, missioncontrol/etl/measure.py, missioncontrol/etl/measuresummary.py, tests/test_api.py, tests/test_api_experiment.py, tests/test_measuresummary.py
More or less just a bunch of random stuff that needed to be fixed + some annotations to make errors easier to track down in the future.
=> Various fixes

missioncontrol/etl/experiment.py, missioncontrol/etl/measure.py
=> Restrict athena queries by submission_date (fixes #227)

missioncontrol/settings.py
This will hopefully fix #230 for reals.
=> Give celery tasks another 5 minutes to complete

frontend/global.css, frontend/schema.js, frontend/ui/mainview.jsx, frontend/ui/subview.jsx, missioncontrol/api/views.py, missioncontrol/etl/measure.py, missioncontrol/etl/measuresummary.py, missioncontrol/etl/versions.py, missioncontrol/settings.py, package.json, setup.cfg, tests/test_api.py, tests/test_etl_measure.py, tests/test_measuresummary.py, yarn.lock
* Comparison is now across last two major versions + latest beta / point release
* Main page now shows major crash trends + deltas, color coded if
appropriate
=> Completely revised measure summaries (fixes #226, #210)

frontend/global.css, frontend/ui/mainview.jsx, package.json, yarn.lock
* Use proper geometric mean for summary rates (i.e. take the nth root of
the child rates)
* Add a copypaste button for easily copying summary rate (+ breakdown
per platform) into meeting notes or wherever
=> Refine summary scores

missioncontrol/etl/builds.py
We can assume that anything older than that we've already ingested, under
most circumstances.
=> Constrain buildhub query to builds new within last week

frontend/ui/dashboard.jsx
* Define what `rate` means
* Make dismissing the modal work again
=> Help modal tweaks/fixes

missioncontrol/settings.py
We're not using this data anywhere right now, so let's not pointlessly
query athena for it.
=> Disable updating experiment data for now

frontend/ui/measuretable.jsx, frontend/ui/subview.jsx
We should only sort the measures into categories *after* we are sure the
data has been downloaded locally.
=> Fix race in categorization code

.neutrinorc.js, README.md, bin/build, bin/run, frontend/test/reducers/reducers.spec.js, package.json, yarn.lock
=> Set up Jest tests for React-Redux

frontend/test/reducers/reducers.spec.js
Towards #317.
Added more tests for reducers.
@wlach
=> Added Jest testing for reducers

frontend/test/components/__snapshots__/measuretable.spec.jsx.snap, frontend/test/components/measuretable.spec.jsx, package.json, yarn.lock
@wlach I have written one test for the component `measureTable`. How should we get the `sampleMeasures` and `sampleVersions` for testing? I have used one sample value but how I can use the actions and reducers to fetch it inside the test?
=> Adds Test for measureTable component

frontend/test/components/__snapshots__/platformcard.spec.jsx.snap, frontend/test/components/platformcard.spec.jsx
Towards #317.
Added Jest test for platformcard component.
@wlach please review.
=> Added Jest test for platformCard component

frontend/test/version.spec.js
Fixes #344. 
Added Jest test for the versioning code. 
@wlach please review.
=> Added Jest test for semVerCompare function

frontend/test/components/subview.spec.jsx, frontend/ui/subview.jsx
Fixes #349.
Added code to persist adjusted/overall distinction in the url.
Also fixes lint errors.
@wlach please review.
=> Persist adjusted/overall distinction in url

frontend/ui/subview.jsx
This is more commonly what people want to see, it seems, so let's
make it the default.
=> Make "all" the default rate calculation in the subview

missioncontrol/etl/measure.py, missioncontrol/etl/measuresummary.py
This should make sure that this time consuming step doesn't time out
=> Have a seperate celery task for updating each measure summary

missioncontrol/etl/measuresummary.py, missioncontrol/etl/versions.py
=> Have fennec always use the esr version when calculating measure summaries
